addons:
  artifacts:
    debug: true
    paths:
    - libs.zip
    - build.zip
    - testbuild.zip
    target_paths: bfb5cb92-6b93-418a-8e4e-228da39f6e4f
after_success:
- ./df-build.sh
before_install:
- sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g'
  $HOME/.m2/settings.xml
branches: ''
cache:
  directories:
  - $HOME/.m2
jdk:
- oraclejdk8
language: java
notifications:
  webhooks:
    on_failure: always
    on_start: always
    on_success: always
    urls:
    - http://insights-portal-insights-service-webserver-dev.public-swarm.devfactory.com/travisWebHookListener?build_id=bfb5cb92-6b93-418a-8e4e-228da39f6e4f
script: mvn test-compile -Dgpg.skip=true -Dlicense.skip=true
# Modified by Insights Service at 2016-10-24 15:30:21.804686
